/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dnd.cs;

import javax.swing.DefaultListModel;

/**
 *
 * @author Dante
 */
public class CharFrame extends javax.swing.JFrame {

    /**
     * Creates new form CharFrame
     */
    public static DnDCS currSheet = new DnDCS();
    public static String[] lists;
    public static DefaultListModel<String> model; 

    public CharFrame() {
        /* Not worth overlaying picture with swing the controll is non existant
        BufferedImage img = null;
        try {
            img = ImageIO.read(new File("src/main/resources/CharacterSheet.jpg"));
        } catch (IOException e) {
        }
        Image dimg = img.getScaledInstance(801, 768, Image.SCALE_SMOOTH);
        ImageIcon imageIcon = new ImageIcon(dimg);
        setContentPane(new JLabel(imageIcon));
        */
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CharNamePane = new javax.swing.JPanel();
        jCharNameField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButtonSaveForm = new javax.swing.JButton();
        jPanelTRGroup = new javax.swing.JPanel();
        jClasslField = new javax.swing.JTextField();
        jLevelField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jBackgroundField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jAligmentField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jExpField = new javax.swing.JTextField();
        jPlayerNameField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jRaceField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jDexterity1 = new javax.swing.JPanel();
        jIntelligenceField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jIntMod = new javax.swing.JTextField();
        jConstitution = new javax.swing.JPanel();
        jConstitutionField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jConMod = new javax.swing.JTextField();
        jDexterity = new javax.swing.JPanel();
        jDexterityField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jDexMod = new javax.swing.JTextField();
        jStrength = new javax.swing.JPanel();
        jStrengthField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jStrMod = new javax.swing.JTextField();
        jDexterity2 = new javax.swing.JPanel();
        jCharismaField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCharismaMod = new javax.swing.JTextField();
        jConstitution1 = new javax.swing.JPanel();
        jWisdomField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jWisdomMod = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 801, 768));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(java.awt.Color.red);

        jPanel1.setAutoscrolls(true);
        jPanel1.setMaximumSize(new java.awt.Dimension(801, 768));
        jPanel1.setOpaque(false);

        CharNamePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jCharNameField.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jCharNameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jCharNameField.setToolTipText("Insert character name");
        jCharNameField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jCharNameField.setMaximumSize(new java.awt.Dimension(20, 30));
        jCharNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCharNameFieldActionPerformed(evt);
            }
        });
        CharNamePane.add(jCharNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 200, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Character Name");
        CharNamePane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jButtonSaveForm.setText("S");
        jButtonSaveForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveFormActionPerformed(evt);
            }
        });

        jPanelTRGroup.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jClasslField.setEditable(false);
        jClasslField.setBackground(new java.awt.Color(255, 255, 255));
        jClasslField.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jClasslField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jClasslField.setToolTipText("Class");
        jClasslField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jClasslFieldActionPerformed(evt);
            }
        });

        jLevelField.setEditable(false);
        jLevelField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jLevelField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLevelFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Class & Level");

        jButton2.setText("...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jBackgroundField.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jBackgroundField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jBackgroundField.setToolTipText("Background");

        jLabel12.setText("Background");

        jAligmentField.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jAligmentField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jAligmentField.setToolTipText("Background");

        jLabel3.setText(" Aligment");

        jExpField.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jExpField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jExpField.setToolTipText("Class & Level");

        jPlayerNameField.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jPlayerNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPlayerNameField.setToolTipText("Class & Level");

        jLabel11.setText("Player Name");

        jRaceField.setFont(new java.awt.Font("Vivaldi", 0, 24)); // NOI18N
        jRaceField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jRaceField.setToolTipText("Class & Level");
        jRaceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRaceFieldActionPerformed(evt);
            }
        });

        jLabel2.setText(" Race");

        jLabel13.setText("Experience Points");

        javax.swing.GroupLayout jPanelTRGroupLayout = new javax.swing.GroupLayout(jPanelTRGroup);
        jPanelTRGroup.setLayout(jPanelTRGroupLayout);
        jPanelTRGroupLayout.setHorizontalGroup(
            jPanelTRGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTRGroupLayout.createSequentialGroup()
                .addGroup(jPanelTRGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTRGroupLayout.createSequentialGroup()
                        .addGroup(jPanelTRGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelTRGroupLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelTRGroupLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jClasslField, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLevelField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTRGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBackgroundField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelTRGroupLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel12))))
                    .addGroup(jPanelTRGroupLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanelTRGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTRGroupLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRaceField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelTRGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelTRGroupLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jAligmentField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanelTRGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTRGroupLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelTRGroupLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelTRGroupLayout.createSequentialGroup()
                        .addGroup(jPanelTRGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jExpField, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPlayerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))))
        );
        jPanelTRGroupLayout.setVerticalGroup(
            jPanelTRGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTRGroupLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTRGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelTRGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBackgroundField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPlayerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelTRGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jClasslField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(jLevelField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)))
                .addGap(10, 10, 10)
                .addGroup(jPanelTRGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTRGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jAligmentField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRaceField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jExpField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelTRGroupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jDexterity1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jIntelligenceField.setEditable(false);
        jIntelligenceField.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jIntelligenceField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jIntelligenceField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jIntelligenceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIntelligenceFieldActionPerformed(evt);
            }
        });

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("INTEL");
        jLabel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jIntMod.setEditable(false);
        jIntMod.setFont(new java.awt.Font("Vivaldi", 1, 12)); // NOI18N
        jIntMod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jIntMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jIntMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jIntModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDexterity1Layout = new javax.swing.GroupLayout(jDexterity1);
        jDexterity1.setLayout(jDexterity1Layout);
        jDexterity1Layout.setHorizontalGroup(
            jDexterity1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDexterity1Layout.createSequentialGroup()
                .addGroup(jDexterity1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDexterity1Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jIntelligenceField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDexterity1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jIntMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDexterity1Layout.setVerticalGroup(
            jDexterity1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDexterity1Layout.createSequentialGroup()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jIntelligenceField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jIntMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jConstitution.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jConstitutionField.setEditable(false);
        jConstitutionField.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jConstitutionField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jConstitutionField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jConstitutionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConstitutionFieldActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("CONST");
        jLabel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jConMod.setEditable(false);
        jConMod.setFont(new java.awt.Font("Vivaldi", 1, 12)); // NOI18N
        jConMod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jConMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jConMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jConstitutionLayout = new javax.swing.GroupLayout(jConstitution);
        jConstitution.setLayout(jConstitutionLayout);
        jConstitutionLayout.setHorizontalGroup(
            jConstitutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jConstitutionLayout.createSequentialGroup()
                .addGroup(jConstitutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jConstitutionLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jConMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jConstitutionLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jConstitutionField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(11, Short.MAX_VALUE))
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jConstitutionLayout.setVerticalGroup(
            jConstitutionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jConstitutionLayout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jConstitutionField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jConMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDexterity.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jDexterityField.setEditable(false);
        jDexterityField.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jDexterityField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jDexterityField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jDexterityField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDexterityFieldActionPerformed(evt);
            }
        });

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("DEXTERITY");
        jLabel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jDexMod.setEditable(false);
        jDexMod.setFont(new java.awt.Font("Vivaldi", 1, 12)); // NOI18N
        jDexMod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jDexMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jDexMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDexModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDexterityLayout = new javax.swing.GroupLayout(jDexterity);
        jDexterity.setLayout(jDexterityLayout);
        jDexterityLayout.setHorizontalGroup(
            jDexterityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDexterityLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDexterityField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
            .addGroup(jDexterityLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jDexMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDexterityLayout.setVerticalGroup(
            jDexterityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDexterityLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDexterityField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDexMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jStrength.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jStrengthField.setEditable(false);
        jStrengthField.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jStrengthField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jStrengthField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jStrengthField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStrengthFieldActionPerformed(evt);
            }
        });

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("STRENGTH");
        jLabel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jStrMod.setEditable(false);
        jStrMod.setFont(new java.awt.Font("Vivaldi", 1, 12)); // NOI18N
        jStrMod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jStrMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jStrMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStrModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jStrengthLayout = new javax.swing.GroupLayout(jStrength);
        jStrength.setLayout(jStrengthLayout);
        jStrengthLayout.setHorizontalGroup(
            jStrengthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jStrengthLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jStrengthField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
            .addGroup(jStrengthLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jStrMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jStrengthLayout.setVerticalGroup(
            jStrengthLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jStrengthLayout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jStrengthField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jStrMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jDexterity2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jCharismaField.setEditable(false);
        jCharismaField.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jCharismaField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jCharismaField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jCharismaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCharismaFieldActionPerformed(evt);
            }
        });

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CHARISMA");
        jLabel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jCharismaMod.setEditable(false);
        jCharismaMod.setFont(new java.awt.Font("Vivaldi", 1, 12)); // NOI18N
        jCharismaMod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jCharismaMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jCharismaMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCharismaModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDexterity2Layout = new javax.swing.GroupLayout(jDexterity2);
        jDexterity2.setLayout(jDexterity2Layout);
        jDexterity2Layout.setHorizontalGroup(
            jDexterity2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDexterity2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCharismaField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
            .addGroup(jDexterity2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jCharismaMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDexterity2Layout.setVerticalGroup(
            jDexterity2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDexterity2Layout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCharismaField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jCharismaMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jConstitution1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jWisdomField.setEditable(false);
        jWisdomField.setFont(new java.awt.Font("Vivaldi", 0, 36)); // NOI18N
        jWisdomField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jWisdomField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jWisdomField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWisdomFieldActionPerformed(evt);
            }
        });

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("WISDOM");
        jLabel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jWisdomMod.setEditable(false);
        jWisdomMod.setFont(new java.awt.Font("Vivaldi", 1, 12)); // NOI18N
        jWisdomMod.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jWisdomMod.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jWisdomMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jWisdomModActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jConstitution1Layout = new javax.swing.GroupLayout(jConstitution1);
        jConstitution1.setLayout(jConstitution1Layout);
        jConstitution1Layout.setHorizontalGroup(
            jConstitution1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jConstitution1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jWisdomField, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
            .addGroup(jConstitution1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jWisdomMod, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jConstitution1Layout.setVerticalGroup(
            jConstitution1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jConstitution1Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jWisdomField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jWisdomMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jStrength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDexterity, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jConstitution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDexterity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jConstitution1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jDexterity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDexterity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jStrength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDexterity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jConstitution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDexterity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jConstitution1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Dungeons&Dragons  5e");

        jButton1.setText("Base Stats");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CharNamePane, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTRGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSaveForm, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanelTRGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 414, Short.MAX_VALUE)
                        .addComponent(jButtonSaveForm, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CharNamePane, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCharNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCharNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCharNameFieldActionPerformed

    private void jButtonSaveFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveFormActionPerformed
        currSheet.charName = jCharNameField.getText();
        currSheet.playerName = jPlayerNameField.getText();
        //currSheet.classAndLevel.level = Integer.parseInt(jLevelField.getText());
        //need to implement class code
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSaveFormActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ClassNLevel classNLevel = new ClassNLevel(this, true);
        classNLevel.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLevelFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLevelFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLevelFieldActionPerformed

    private void jRaceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRaceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRaceFieldActionPerformed

    private void jStrModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStrModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jStrModActionPerformed

    private void jStrengthFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStrengthFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jStrengthFieldActionPerformed

    private void jDexterityFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDexterityFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDexterityFieldActionPerformed

    private void jDexModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDexModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jDexModActionPerformed

    private void jIntelligenceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIntelligenceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIntelligenceFieldActionPerformed

    private void jIntModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jIntModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jIntModActionPerformed

    private void jConstitutionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConstitutionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jConstitutionFieldActionPerformed

    private void jConModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jConModActionPerformed

    private void jCharismaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCharismaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCharismaFieldActionPerformed

    private void jCharismaModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCharismaModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCharismaModActionPerformed

    private void jWisdomFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWisdomFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jWisdomFieldActionPerformed

    private void jWisdomModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jWisdomModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jWisdomModActionPerformed

    private void jClasslFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jClasslFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jClasslFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        BaseStats baseStats = new BaseStats(this, true);
        baseStats.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CharFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CharFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CharFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CharFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CharFrame().setVisible(true);
            }
        });
    }
    
    public static void refreshStatsAndMods(){
       
        CharFrame.jStrengthField.setText(String.valueOf(currSheet.stats.STRENGTH.getValue()));
        CharFrame.jStrMod.setText("+" + String.valueOf(currSheet.stats.STRENGTH.getModifier()));
        
        CharFrame.jDexterityField.setText(String.valueOf(currSheet.stats.DEXTERITY.getValue()));
        CharFrame.jDexMod.setText("+" + String.valueOf(currSheet.stats.DEXTERITY.getModifier()));
        
        CharFrame.jConstitutionField.setText(String.valueOf(currSheet.stats.CONSTITUTION.getValue()));
        CharFrame.jConMod.setText("+" + String.valueOf(currSheet.stats.CONSTITUTION.getModifier()));
        
        CharFrame.jIntelligenceField.setText(String.valueOf(currSheet.stats.INTELIGENCE.getValue()));
        CharFrame.jIntMod.setText("+" + String.valueOf(currSheet.stats.INTELIGENCE.getModifier()));
        
        CharFrame.jWisdomField.setText(String.valueOf(currSheet.stats.WISDOM.getValue()));
        CharFrame.jWisdomMod.setText("+" + String.valueOf(currSheet.stats.WISDOM.getModifier()));
        
        CharFrame.jCharismaField.setText(String.valueOf(currSheet.stats.CHARISMA.getValue()));
        CharFrame.jCharismaMod.setText("+" + String.valueOf(currSheet.stats.INTELIGENCE.getModifier()));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CharNamePane;
    private javax.swing.JTextField jAligmentField;
    private javax.swing.JTextField jBackgroundField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonSaveForm;
    private javax.swing.JTextField jCharNameField;
    public static javax.swing.JTextField jCharismaField;
    public static javax.swing.JTextField jCharismaMod;
    public static javax.swing.JTextField jClasslField;
    public static javax.swing.JTextField jConMod;
    private javax.swing.JPanel jConstitution;
    private javax.swing.JPanel jConstitution1;
    public static javax.swing.JTextField jConstitutionField;
    public static javax.swing.JTextField jDexMod;
    private javax.swing.JPanel jDexterity;
    private javax.swing.JPanel jDexterity1;
    private javax.swing.JPanel jDexterity2;
    public static javax.swing.JTextField jDexterityField;
    private javax.swing.JTextField jExpField;
    public static javax.swing.JTextField jIntMod;
    public static javax.swing.JTextField jIntelligenceField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JTextField jLevelField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelTRGroup;
    private javax.swing.JTextField jPlayerNameField;
    private javax.swing.JTextField jRaceField;
    public static javax.swing.JTextField jStrMod;
    private javax.swing.JPanel jStrength;
    public static javax.swing.JTextField jStrengthField;
    public static javax.swing.JTextField jWisdomField;
    public static javax.swing.JTextField jWisdomMod;
    // End of variables declaration//GEN-END:variables
}
